mk_louvre_homepage:
    path:     /
    defaults: { _controller: MKLouvreBundle:Default:index }

mk_louvre_inscription:
    path:     /reservation
    defaults: { _controller: MKLouvreBundle:Default:reservation }
mk_louvre_ticket:
    path:     /ticket
    defaults: { _controller: MKLouvreBundle:Default:ticket }