services:
    mk_louvre.reference:
        class: MK\LouvreBundle\Reference\MKReference 

    mk_louvre.validator.blocage:
        class: MK\LouvreBundle\Validator\BlocageValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]        
        tags:
            - { name: validator.constraint_validator, alias: mk_louvre_blocage }

 