services:
    mk_louvre.reference:
        class: MK\LouvreBundle\Reference\MKReference 

    mk_louvre.tarif:
        class: MK\LouvreBundle\CalculTarif\MKTarif

    mk_louvre.limit:
        class: MK\LouvreBundle\Billet\MKLimit

    mk_louvre.billet:
        class: MK\LouvreBundle\Billet\MKBillet




 