<?php

namespace MK\LouvreBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
	public function limitationReservation($date)
	{


		$qb = $this->createQueryBuilder('a');

		$qb
		->select('SUM(a.nbBillet)')
		->where('a.dtReservation = :date')
		   ->setParameter('date', $date)
		;
//dump($qb); die();
		return $qb
		->getQuery()
		->getResult()
		;


	}
}
